### ISSUE TITLE
Changes in crowd behavior in WOR+

### ISSUE THREAD

**Issue by CrashedNLanded** [JamesIsWack/WoRmod#1]

**Comment by CrashedNLanded** [comment]
FORGOT TO ADD DESCRIPTION XD.....   The crowd behavior got nerfed in WOR+, i'm on 0.3c but it also happens on 0.4c.

On any non-WOR song on the setlist, the crowd normally is cheering when in green on vanilla, but on WOR+ they don't cheer unless a script in the song gets them to cheer or I guess that's how it works, but crowds for non-WOR songs (GH5 exports for example) To know what I mean, what one of aWiseMoose's Guitar hero DLC runs on WOR and you can see the crowd always cheering in green but not in WOR+

**Comment by kernaltrap8** [comment]
Sorry I didn't get back to this sooner. Im working on some things, but I will test this in a moment. I have not noticed any difference myself. Do you maybe have the crowd audio too low to hear?

**Comment by CrashedNLanded** [comment]
Hey its way late, but i figured i installed the mod wrong, its fine now
